### ISSUE TITLE
can_create_object? permission location

### ISSUE THREAD

**Issue by jimmytang** [palkan/action_policy-graphql#30]
Hi @palkan ,

Big fan of your work! I'm trying to set up authorization on my project and while it's clear to place the permissions inline when there is an object (edit, destroy), it's less obvious where to put permissions for index and create, which are at the class level. 

One way is to place them inside a Type::PermissionType class.

How would you recommend organizing this? Thank you

**Comment by palkan** [comment]
Usually, I add such fields to the _parent_ type, for example:

```ruby
module Types
  class Room < Base
     # whether user is allowed to send messages to this chat room 
     expose_authorization_rules :create?, with: MessagePolicy, field_name: :can_create_messages
  end
end
```

The top-level _parent_ could be `me` (or `viewer`) type.

**Comment by dmitry** [comment]
We are doing the same. Alternatively you can use plain `allowed_to?` if authorization rules are too big for you:

```ruby
      field :can_manage_jobs, Boolean, null: false
      def can_manage_jobs
        allowed_to?(:manage?, ::Job)
      end
```

**Comment by luccasmaso** [comment]
Hey everyone! I have a follow-up question about best practices for setting up policies, if you're willing to share your thoughts.

First off, this is an awesome library, and I’m currently using `expose_authorization_rules` to help better manage permissions on the frontend. In the example you shared above, I see the `create?` action lives inside the `MessagePolicy`. I'm wondering when it’s more convenient to put the action there instead of `RoomPolicy#create_messages`. 

From what I can think of off the top of my head, one immediate benefit of putting the action inside the `MessagePolicy` is that it would automatically plug into `expose_authorization_rules` without needing a `with`. However, the downside that’s been on my mind is if the action is inside the `MessagePolicy` and it needs to check something on the room (like whether the room is active or not), the `record` in the `MessagePolicy` would be the message object, not the room itself:

```ruby
class MessagePolicy < ApplicationPolicy
  def create?
    record.active?
  end
end
```

As you can see, `record` here is actually a room, but it’s not super obvious.

```ruby
class RoomPolicy < ApplicationPolicy
  def create_message?
    record.active?
  end
end
```

I’m curious which design might be a better fit long-term as the number of policies and rules grows. Appreciate any insights!

**Comment by palkan** [comment]
Hey @luccasmaso,

In this particular scenario, I would probably go with an additional authorization context:

```ruby
class MessagePolicy < ApplicationPolicy
  authorize :room, optional: true

  def create?
    room&.active?
  end
end

# and then you add the following to the type class
authorize :room
```

Usually, the `#create?` rule is equal to the `#manage?` rule on the context object (e.g., `room`), so I would expose it as follows:

```ruby
expose_authorization_rules :manage?, field_name: :can_create_messages

# we need to define the field explicitly to pass the context object, not the current one
def can_create_messages = allowance_to(:manage?, object.room)
```
